// <auto-generated />
using System;
using LeagueMatchHistory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeagueMatchHistory.Migrations
{
    [DbContext(typeof(LeagueMatchHistoryContext))]
    [Migration("20210509151430_SummonerAccountInfoFixAttempt1")]
    partial class SummonerAccountInfoFixAttempt1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeagueMatchHistory.Models.Summoner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("FreshBlood")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("HotStreak")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Inactive")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LeagueId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LeaguePoints")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Losses")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ProfileIconId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PuuId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("QueueType")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Rank")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RevisionDate")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerLevel")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerName")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Tier")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Veteran")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Wins")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("ID");

                    b.ToTable("Summoner");
                });

            modelBuilder.Entity("LeagueMatchHistory.Models.SummonerAccountInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileIconId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PuuId")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("RecordCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevisionDate")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerLevel")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerName")
                        .HasColumnType("varchar(512)");

                    b.HasKey("ID");

                    b.ToTable("SummonerAccountInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
