// <auto-generated />
using System;
using LeagueMatchHistory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeagueMatchHistory.Migrations
{
    [DbContext(typeof(LeagueMatchHistoryContext))]
    [Migration("20210512051434_MatchListMigration1")]
    partial class MatchListMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeagueMatchHistory.Models.MatchInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataVersion")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("GameCreation")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("GameDuration")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("GameMode")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("GameName")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("GameStartTimeStamp")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("GameType")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("GameVersion")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("MatchId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PlatformId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("QueueId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("ID");

                    b.ToTable("MatchInfo");
                });

            modelBuilder.Entity("LeagueMatchHistory.Models.MatchList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MatchId")
                        .HasColumnType("varchar(512)");

                    b.HasKey("ID");

                    b.ToTable("MatchList");
                });

            modelBuilder.Entity("LeagueMatchHistory.Models.ParticipantInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MatchId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary0")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary0Var1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary0Var2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary0Var3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary1Var1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary1Var2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary1Var3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary2Var1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary2Var2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary2Var3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary3Var1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary3Var2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimary3Var3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkPrimaryStyle")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkSeconday0")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkSeconday0Var1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkSeconday0Var2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkSeconday0Var3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkSeconday1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkSeconday1Var1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkSeconday1Var2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkSeconday1Var3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PerkSecondayStyle")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("StatPerks1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("StatPerks2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("StatPerks3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("assists")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("baronKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("bountyLevel")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("champExperience")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("champLevel")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("championId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("championName")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("championTransform")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("consumablesPurchased")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("damageDealtToBuildings")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("damageDealtToObjectives")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("damageDealtToTurrets")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("damageSelfMitigated")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("deaths")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("detectorWardsPlaced")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("doubleKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("dragonKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("firstBloodAssist")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("firstBloodKill")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("firstTowerAssist")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("firstTowerKill")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("gameEndedInEarlySurrender")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("gameEndedInSurrender")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("goldEarned")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("goldSpent")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("individualPosition")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("inhibitorKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("inhibitorsLost")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("item0")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("item1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("item2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("item3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("item4")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("item5")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("item6")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("itemsPurchased")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("killingSprees")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("kills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("lane")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("largestCriticalStrike")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("largestKillingSpree")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("largestMultiKill")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("longestTimeSpentLiving")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("magicDamageDealt")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("magicDamageDealtToChampions")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("magicDamageTaken")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("neutralMinionsKilled")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("nexusKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("nexusLost")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("objectivesStolen")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("objectivesStolenAssists")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("participantId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("pentaKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("physicalDamageDealt")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("physicalDamageDealtToChampions")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("physicalDamageTaken")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("profileIcon")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("puuid")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("quadraKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("riotIdName")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("riotIdTagline")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("role")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("sightwardsBoughtInGame")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("spell1Casts")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("spell2Casts")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("spell3Casts")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("spell4casts")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("summoner1Casts")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("summoner1Id")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("summoner2Casts")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("summoner2Id")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("summonerId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("summonerLevel")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("summonerName")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("teamEarlySurrendered")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("teamId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("teamPosition")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("timeCCingOthers")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("timePlayed")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalDamageDealt")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalDamageDealtToChampions")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalDamageShieldedOnTeammates")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalDamageTaken")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalHeal")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalHealsOnTeammates")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalMinionsKilled")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalTimeCCDealt")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalTimeSpentDead")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("totalUnitsHealed")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("tripleKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("trueDamageDealt")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("trueDamageDealtToChampions")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("trueDamageTaken")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("turretKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("turretsLost")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("unrealKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("visionScore")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("visionWardsBoughtInGame")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("wardsKilled")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("wardsPlaced")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("win")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("ID");

                    b.ToTable("ParticipantInfo");
                });

            modelBuilder.Entity("LeagueMatchHistory.Models.RankedInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FreshBlood")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("HotStreak")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Inactive")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeagueId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LeaguePoints")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Losses")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("QueueType")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Rank")
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("SummonerAccountInfoID")
                        .HasColumnType("int");

                    b.Property<string>("SummonerId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerName")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Tier")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Veteran")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Wins")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("ID");

                    b.HasIndex("SummonerAccountInfoID");

                    b.ToTable("RankedInfo");
                });

            modelBuilder.Entity("LeagueMatchHistory.Models.SummonerAccountInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileIconId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PuuId")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("RecordCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevisionDate")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerLevel")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SummonerName")
                        .HasColumnType("varchar(512)");

                    b.HasKey("ID");

                    b.ToTable("SummonerAccountInfo");
                });

            modelBuilder.Entity("LeagueMatchHistory.Models.TeamsInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ban0")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Ban1")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Ban2")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Ban3")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Ban4")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("BaronKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ChampionKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("DragonKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("FirstBaron")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("FirstBlood")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("FirstDragon")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("FirstInhibitor")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("FirstRitHerald")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("FirstTower")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("InhibitorKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("MatchId")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RiftHeraldKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("TowerKills")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Win")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("ID");

                    b.ToTable("TeamsInfo");
                });

            modelBuilder.Entity("LeagueMatchHistory.Models.RankedInfo", b =>
                {
                    b.HasOne("LeagueMatchHistory.Models.SummonerAccountInfo", "SummonerAccountInfo")
                        .WithMany()
                        .HasForeignKey("SummonerAccountInfoID");

                    b.Navigation("SummonerAccountInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
